clc; clear; close all;

% ----------------------- Generate Synthetic Data -----------------------
dt = 4e-3;
Nsteps = 2500;
t = (0:Nsteps-1) * dt;

f_CM = 1;
f_KK = 2;

amp_CM = 0.8;
amp_KK = 0.3;

CM = amp_CM * sin(2*pi*f_CM*t);
KK = amp_KK * sin(2*pi*f_KK*t);

% Back-calculate chromatid positions
cL(:,1,1) = CM - KK/2;
cL(:,2,1) = 0;
cR(:,1,1) = CM + KK/2;
cR(:,2,1) = 0;

% ----------------------- Calculate Trajectories -----------------------
CM_x = (cL(:,1,1) + cR(:,1,1)) / 2;
KK_x = cR(:,1,1) - cL(:,1,1);

% ----------------------- Plot Oscillations -----------------------
figure;
plot(t, CM_x, 'k', 'LineWidth', 2); hold on;
plot(t, KK_x, 'm', 'LineWidth', 2);
legend('CM', 'KK');
xlabel('Time (min)');
ylabel('Position (µm)');
title('Synthetic CM and KK Oscillations');
grid on;

% ----------------------- Peak and Valley Detection -----------------------
[CM_peaks, CM_peak_locs] = findpeaks(CM_x, 'MinPeakProminence', 0.1);
[CM_valleys, CM_valley_locs] = findpeaks(-CM_x, 'MinPeakProminence', 0.1); CM_valleys = -CM_valleys;

[KK_peaks, KK_peak_locs] = findpeaks(KK_x, 'MinPeakProminence', 0.1);
[KK_valleys, KK_valley_locs] = findpeaks(-KK_x, 'MinPeakProminence', 0.1); KK_valleys = -KK_valleys;

% ----------------------- Visualize Peaks and Valleys -----------------------
plot(t(CM_peak_locs), CM_peaks, 'ko', 'MarkerFaceColor', 'g');
plot(t(CM_valley_locs), CM_valleys, 'ks', 'MarkerFaceColor', 'y');
plot(t(KK_peak_locs), KK_peaks, 'mo', 'MarkerFaceColor', 'c');
plot(t(KK_valley_locs), KK_valleys, 'ms', 'MarkerFaceColor', 'w');

% ----------------------- Set Meta Info -----------------------
iter = 1;
chr = 1;

% ----------------------- Raw Table -----------------------
T_Raw_CM = table(...
    [t(CM_peak_locs)'; t(CM_valley_locs)'], ...
    [CM_peaks; CM_valleys], ...
    [repmat("peak", length(CM_peaks), 1); repmat("valley", length(CM_valleys), 1)], ...
    repmat("CM", length(CM_peaks)+length(CM_valleys), 1), ...
    repmat(chr, length(CM_peaks)+length(CM_valleys), 1), ...
    repmat(iter, length(CM_peaks)+length(CM_valleys), 1), ...
    'VariableNames', {'time', 'value', 'type', 'metric', 'chromosome', 'iteration'});
T_Raw_CM = sortrows(T_Raw_CM , 'time');

T_Raw_KK = table(...
    [t(KK_peak_locs)'; t(KK_valley_locs)'], ...
    [KK_peaks; KK_valleys], ...
    [repmat("peak", length(KK_peaks), 1); repmat("valley", length(KK_valleys), 1)], ...
    repmat("KK", length(KK_peaks)+length(KK_valleys), 1), ...
    repmat(chr, length(KK_peaks)+length(KK_valleys), 1), ...
    repmat(iter, length(KK_peaks)+length(KK_valleys), 1), ...
    'VariableNames', {'time', 'value', 'type', 'metric', 'chromosome', 'iteration'});
T_Raw_KK = sortrows(T_Raw_KK , 'time');
table_raw_all = [T_Raw_CM; T_Raw_KK];

% ----------------------- Cycle Table -----------------------
%  Amplitude Tables 
N_CM_amp = min(length(CM_peaks), length(CM_valleys));
T_amplitude_CM = table(...
    (1:N_CM_amp)', ...
    repmat(chr, N_CM_amp, 1), ...
    repmat(iter, N_CM_amp, 1), ...
    repmat("CM", N_CM_amp, 1), ...
    (CM_peaks(1:N_CM_amp) - CM_valleys(1:N_CM_amp)) / 2, ...
    'VariableNames', {'cycle_id', 'chromosome', 'iteration', 'metric', 'amplitude'});

N_KK_amp = min(length(KK_peaks), length(KK_valleys));
T_amplitude_KK = table(...
    (1:N_KK_amp)', ...
    repmat(chr, N_KK_amp, 1), ...
    repmat(iter, N_KK_amp, 1), ...
    repmat("KK", N_KK_amp, 1), ...
    (KK_peaks(1:N_KK_amp) - KK_valleys(1:N_KK_amp)) / 2, ...
    'VariableNames', {'cycle_id', 'chromosome', 'iteration', 'metric', 'amplitude'});

%  Period Tables 
N_CM_period = length(CM_peak_locs) - 1;
T_period_CM = table(...
    (1:N_CM_period)', ...
    repmat(chr, N_CM_period, 1), ...
    repmat(iter, N_CM_period, 1), ...
    repmat("CM", N_CM_period, 1), ...
    diff(t(CM_peak_locs)'), ...
    'VariableNames', {'cycle_id', 'chromosome', 'iteration', 'metric', 'period'});

N_KK_period = length(KK_peak_locs) - 1;
T_period_KK = table(...
    (1:N_KK_period)', ...
    repmat(chr, N_KK_period, 1), ...
    repmat(iter, N_KK_period, 1), ...
    repmat("KK", N_KK_period, 1), ...
    diff(t(KK_peak_locs)'), ...
    'VariableNames', {'cycle_id', 'chromosome', 'iteration', 'metric', 'period'});

% Merge CM amplitude and period tables
T_cycles_CM = innerjoin(T_amplitude_CM, T_period_CM, ...
    'Keys', {'cycle_id', 'chromosome', 'iteration', 'metric'});

% Merge KK amplitude and period tables
T_cycles_KK = innerjoin(T_amplitude_KK, T_period_KK, ...
    'Keys', {'cycle_id', 'chromosome', 'iteration', 'metric'});

% Combine into one cycles table
table_cycles = [T_cycles_CM; T_cycles_KK];


% ----------------------- Summary Table -----------------------
table_summary = groupsummary(table_cycles, ...
    {'iteration', 'chromosome', 'metric'}, ...
    ["mean", "std"], ["amplitude", "period"]);
